---
# opensuse_leap_micro_add_regular_repositories/tasks/main.yml

- name: 'Set correct releasever variable on openSUSE Leap Micro'
  ansible.builtin.set_fact:
    releasever: '15.4'
  when:
    - 'ansible_os_family == "openSUSE Leap Micro"'
    - 'ansible_distribution_version == "5.3"'

- name: 'Set correct releasever variable on openSUSE Leap 15.4'
  ansible.builtin.set_fact:
    releasever: '$releasever'
  when:
    - 'ansible_os_family == "Suse"'
    - 'ansible_distribution_version == "15.4"'

- name: 'Create standard repositories'
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/zypp/repos.d/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Run zypper refresh'
  loop:
    - 'repo-backports-debug-update.repo'
    - 'repo-backports-update.repo'
    - 'repo-debug-non-oss.repo'
    - 'repo-debug.repo'
    - 'repo-debug-update-non-oss.repo'
    - 'repo-debug-update.repo'
    - 'repo-non-oss.repo'
    - 'repo-oss.repo'
    - 'repo-sle-debug-update.repo'
    - 'repo-sle-update.repo'
    - 'repo-source.repo'
    - 'repo-update-non-oss.repo'
    - 'repo-update.repo'

- name: 'Flush handlers to trigger zypper refresh'
  ansible.builtin.meta: flush_handlers
